// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./.vitepress/components/common-header.vue')['default']
    ConfigurationForm: typeof import('./.vitepress/components/configuration-form.vue')['default']
    CreateButton: typeof import('./.vitepress/components/create-button.vue')['default']
    FormItems: typeof import('./.vitepress/components/form-items.vue')['default']
    PreviewCom: typeof import('./.vitepress/components/preview-com.vue')['default']
    RenderForm: typeof import('./.vitepress/components/render-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
