// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonHeader: typeof import('./.vitepress/components/common-header.vue')['default']
    ConfigurationForm: typeof import('./.vitepress/components/configuration-form.vue')['default']
    CreateButton: typeof import('./.vitepress/components/create-button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FormItems: typeof import('./.vitepress/components/form-items.vue')['default']
    PageAbout: typeof import('./.vitepress/pages/page-about.vue')['default']
    PageHome: typeof import('./.vitepress/components/page-home.vue')['default']
    PagePoster: typeof import('./.vitepress/pages/page-poster.vue')['default']
    PreviewCom: typeof import('./.vitepress/components/preview-com.vue')['default']
    RenderForm: typeof import('./.vitepress/components/render-form.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
